#! /bin/sh

bspc monitor -d Browser Code Social Music Files

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config single_monocle 	      true

bspc config normal_border_color    "#19191C"
bspc config focused_border_color   "#202026"

bspc rule -a firefox desktop="^1"
bspc rule -a code-oss desktop="^2"
bspc rule -a jetbrains-webstorm desktop="^2"
bspc rule -a jetbrains-phpstorm desktop="^2"
bspc rule -a discord desktop="^3"
bspc rule -a TelegramDesktop desktop="^3"
bspc rule -a Thunar desktop="^5"
bspc rule -a krita state=floating

pkill sxhkd
pkill dunst
pkill picom

sxhkd &
feh --bg-scale ~/Walls/14.jpg &
$HOME/.config/polybar/launch.sh &
picom &
dunst &
redshift &
wmname LG3D 
